name=MKE_I2C_DHT20
version=1.0.0
author=MakerEdu.vn
maintainer=MakerEdu.vn
sentence=Library for MKE I2C DHT20 temperature and humidity sensor
paragraph=Provides an easy interface to control the MKE-S11-DHT20-I2C-TEMPERATURE-HUMIDITY-SENSOR module.
category=Sensors
url=https://github.com/makereduvn/MKE-S11-DHT20-I2C-TEMPERATURE-HUMIDITY-SENSOR
architectures=*
includes=MKE_I2C_DHT20.h
